/*
 * FrmBanco.java
 *
 * Created on __DATE__, __TIME__
 */

package winUIPackage;

import java.awt.AWTKeyStroke;
import java.awt.Cursor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.ReplicationMode;
import org.hibernate.Transaction;

import sessionPackage.MySession;

import entitiesPackage.Barcos;
import entitiesPackage.BarcosId;
import entitiesPackage.Entity;
import entitiesPackage.Message;

/**
 *
 * @author  SANTI DIAZ
 */
public class FrmBarco extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	Barcos barco;

	private java.awt.Frame parentFrame;
	private MySession session;
	private boolean OnNew = false;
	private Entity entity = new Entity();

	public java.awt.Frame getParentFrame() {
		return this.parentFrame;
	}

	public void setParentFrame(java.awt.Frame parentFrame) {
		this.parentFrame = parentFrame;
	}

	public void setSession(MySession session) {
		this.session = session;
	}

	public MySession getSession() {
		return session;
	}

	/** Creates new form FrmBanco */
	public FrmBarco() {
		initComponents();
	}

	public FrmBarco(java.awt.Frame parent, MySession session) {
		try {
			initComponents();
			this.parentFrame = parent;
			this.setSession(session);
			entity.setSession(session);
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmBarco()", he);
		}
	}

	private void configureKeys() {
		try {
			Set<AWTKeyStroke> teclasTab = new HashSet<AWTKeyStroke>();
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_DOWN, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_TAB, 0));
			pnlData.setFocusTraversalKeys(
					KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, teclasTab);

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmBarco.configureKeys",
					he);
		}
	}

	public void loadData(Barcos entity) {

		try {
			this.barco = entity;
			txtIdBarco.setValue(entity.getId().getIdBarco());
			txtNombreBarco.setText(entity.getNombreBarco());
			OnNew = false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmBarco.loadData()",
					he);
		}
	}

	public void newData() {
		try {
			this.barco = new Barcos();
			txtIdBarco.setText("");
			txtNombreBarco.setText("");
			OnNew = true;
		} catch (RuntimeException he) {
			Message
					.ShowRuntimeError(this.parentFrame, "FrmBarco.newData()",
							he);
		}

	}

	public boolean saveData(Boolean showmessage) {

		try {
			if (validateData()) {

				Transaction transaction = session.getSession()
						.beginTransaction();
				if (OnNew) {
					txtIdBarco.setValue(entity.newId(this, "Barcos",
							"id.idBarco"));
					BarcosId barcoid = new BarcosId();
					barcoid.setEmpresas(session.getEmpresa());
					barcoid.setEjercicios(session.getEjercicio());
					barcoid.setIdBarco((Integer) txtIdBarco.getValue());
					barco.setId(barcoid);
				}
				if (!txtNombreBarco.getText().equals(""))
					barco.setNombreBarco(txtNombreBarco.getText());
				else
					barco.setNombreBarco(null);
				barco.setLmd(new Date());
				barco.setSid("Santi");
				barco.setVersion(1);
				session.getSession()
						.replicate(barco, ReplicationMode.OVERWRITE);
				session.getSession().saveOrUpdate(barco);
				session.getSession().flush();
				if (!transaction.wasCommitted()) {
					transaction.commit();
				}
				session.getSession().close();
				if (showmessage)
					Message.ShowSaveSuccesfull(pnlData);
				OnNew = false;
				FrmBarcos.runSearchQuery();
				return true;
			}
			else
				return false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmBarco.saveData()",
					he);
			return false;
		}
	}

	private boolean validateData() {

		try {
			if (txtNombreBarco.getText().equals("")) {
				Message.ShowValidateMessage(pnlData,
						"Debe indicar un nombre para el barco.");
				txtNombreBarco.requestFocus();
				return (false);
			}

			return (true);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmBarco.validateData()", he);
			return false;
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pnlData = new javax.swing.JPanel();
		lblIdBarco = new javax.swing.JLabel();
		lblNombreBarco = new javax.swing.JLabel();
		txtNombreBarco = new javax.swing.JTextField();
		btnOk = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();
		txtIdBarco = new javax.swing.JFormattedTextField();

		pnlData.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		pnlData.setName("pnlData");

		lblIdBarco.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblIdBarco.setForeground(new java.awt.Color(255, 0, 0));
		lblIdBarco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblIdBarco.setText("Id barco");

		lblNombreBarco.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblNombreBarco.setForeground(new java.awt.Color(255, 0, 0));
		lblNombreBarco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblNombreBarco.setText("Nombre barco");

		txtNombreBarco.setFont(new java.awt.Font("Segoe UI", 0, 14));
		txtNombreBarco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtNombreBarco.setAutoscrolls(false);
		txtNombreBarco.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtNombreBarco.setName("");
		txtNombreBarco.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtNombreBarcoKeyTyped(evt);
			}
		});

		btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/ok.png"))); // NOI18N
		btnOk.setToolTipText("Aceptar");
		btnOk.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnOkMousePressed(evt);
			}
		});

		btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/cancel.png"))); // NOI18N
		btnCancel.setToolTipText("Cancelar");
		btnCancel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnCancelMousePressed(evt);
			}
		});

		txtIdBarco.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtIdBarco.setEditable(false);
		txtIdBarco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtIdBarco.setFont(new java.awt.Font("Segoe UI", 0, 14));

		javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(
				pnlData);
		pnlData.setLayout(pnlDataLayout);
		pnlDataLayout
				.setHorizontalGroup(pnlDataLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pnlDataLayout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																pnlDataLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblIdBarco,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				120,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				txtIdBarco,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																pnlDataLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblNombreBarco,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				120,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				txtNombreBarco,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				480,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(45, 45, 45))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								pnlDataLayout
										.createSequentialGroup()
										.addContainerGap(548, Short.MAX_VALUE)
										.addComponent(btnCancel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnOk).addContainerGap()));
		pnlDataLayout
				.setVerticalGroup(pnlDataLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pnlDataLayout
										.createSequentialGroup()
										.addGap(72, 72, 72)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																lblIdBarco)
														.addComponent(
																txtIdBarco,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(10, 10, 10)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																lblNombreBarco)
														.addComponent(
																txtNombreBarco,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												71, Short.MAX_VALUE)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(btnOk)
														.addComponent(btnCancel))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 676,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pnlData, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			if (OnNew) 
				newData();
			else
				loadData(this.barco);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmBarco.btnCancelMousePressed()", he);
		}
	}

	private void btnOkMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			saveData(true);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmBarco.btnOkMousePressed()", he);
		}
	}

	private void txtNombreBarcoKeyTyped(java.awt.event.KeyEvent evt) {
		try {
			Util.keyTyped(txtNombreBarco, evt, 25);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmBarco.txtNombreBarcoKeyTyped()", he);
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOk;
	private javax.swing.JLabel lblIdBarco;
	private javax.swing.JLabel lblNombreBarco;
	public javax.swing.JPanel pnlData;
	private javax.swing.JFormattedTextField txtIdBarco;
	private javax.swing.JTextField txtNombreBarco;
	// End of variables declaration//GEN-END:variables

}