/*
 * FrmBanco.java
 *
 * Created on __DATE__, __TIME__
 */

package winUIPackage;

import java.awt.AWTKeyStroke;
import java.awt.Cursor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.ReplicationMode;
import org.hibernate.Transaction;

import sessionPackage.MySession;

import entitiesPackage.Conceptos;
import entitiesPackage.ConceptosId;
import entitiesPackage.Entity;
import entitiesPackage.Message;

/**
 *
 * @author  SANTI DIAZ
 */
public class FrmConcepto extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	Conceptos concepto;

	private java.awt.Frame parentFrame;
	private MySession session;
	private boolean OnNew = false;
	private Entity entity = new Entity();

	public java.awt.Frame getParentFrame() {
		return this.parentFrame;
	}

	public void setParentFrame(java.awt.Frame parentFrame) {
		this.parentFrame = parentFrame;
	}

	public void setSession(MySession session) {
		this.session = session;
	}

	public MySession getSession() {
		return session;
	}

	/** Creates new form FrmBanco */
	public FrmConcepto() {
		initComponents();
	}

	public FrmConcepto(java.awt.Frame parent, MySession session) {
		try {
			initComponents();
			this.parentFrame = parent;
			this.setSession(session);
			entity.setSession(session);
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmConcepto()", he);
		}
	}

	private void configureKeys() {
		try {
			Set<AWTKeyStroke> teclasTab = new HashSet<AWTKeyStroke>();
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_DOWN, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_TAB, 0));
			pnlData.setFocusTraversalKeys(
					KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, teclasTab);

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmConcepto.configureKeys",
					he);
		}
	}

	public void loadData(Conceptos entity) {

		try {
			this.concepto = entity;
			txtIdConcepto.setValue(entity.getId().getConcepto());
			txtConceptoDesc.setText(entity.getConceptoDesc());
			OnNew = false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmConcepto.loadData()",
					he);
		}
	}

	public void newData() {
		try {
			this.concepto = new Conceptos();
			txtIdConcepto.setText("");
			txtConceptoDesc.setText("");
			OnNew = true;
		} catch (RuntimeException he) {
			Message
					.ShowRuntimeError(this.parentFrame, "FrmConcepto.newData()",
							he);
		}

	}

	public boolean saveData(Boolean showmessage) {

		try {
			if (validateData()) {

				Transaction transaction = session.getSession()
						.beginTransaction();
				if (OnNew) {
					txtIdConcepto.setValue(entity.newId(this, "Conceptos",
							"id.concepto"));
					ConceptosId conceptoid = new ConceptosId();
					conceptoid.setEmpresas(session.getEmpresa());
					conceptoid.setEjercicios(session.getEjercicio());
					conceptoid.setConcepto((Integer) txtIdConcepto.getValue());
					concepto.setId(conceptoid);
					concepto.setConIgic((short) 1);
				}
				if (!txtConceptoDesc.getText().equals(""))
					concepto.setConceptoDesc(txtConceptoDesc.getText());
				else
					concepto.setConceptoDesc(null);
				concepto.setLmd(new Date());
				concepto.setSid("Santi");
				concepto.setVersion(1);
				session.getSession()
						.replicate(concepto, ReplicationMode.OVERWRITE);
				session.getSession().saveOrUpdate(concepto);
				session.getSession().flush();
				if (!transaction.wasCommitted()) {
					transaction.commit();
				}
				session.getSession().close();
				if (showmessage)
					Message.ShowSaveSuccesfull(pnlData);
				OnNew = false;
				FrmConceptos.runSearchQuery();
				return true;
			}
			else
				return false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmConcepto.saveData()",
					he);
			return false;
		}
	}

	private boolean validateData() {

		try {
			if (txtConceptoDesc.getText().equals("")) {
				Message.ShowValidateMessage(pnlData,
						"Debe indicar un nombre para el concepto.");
				txtConceptoDesc.requestFocus();
				return (false);
			}

			return (true);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmConcepto.validateData()", he);
			return false;
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pnlData = new javax.swing.JPanel();
		lblIdConcepto = new javax.swing.JLabel();
		lblConceptoDesc = new javax.swing.JLabel();
		txtConceptoDesc = new javax.swing.JTextField();
		btnOk = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();
		txtIdConcepto = new javax.swing.JFormattedTextField();

		pnlData.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		pnlData.setName("pnlData");

		lblIdConcepto.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblIdConcepto.setForeground(new java.awt.Color(255, 0, 0));
		lblIdConcepto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblIdConcepto.setText("Id concepto");

		lblConceptoDesc.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblConceptoDesc.setForeground(new java.awt.Color(255, 0, 0));
		lblConceptoDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblConceptoDesc.setText("Descripción");

		txtConceptoDesc.setFont(new java.awt.Font("Segoe UI", 0, 14));
		txtConceptoDesc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtConceptoDesc.setAutoscrolls(false);
		txtConceptoDesc.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtConceptoDesc.setName("");
		txtConceptoDesc.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				txtConceptoDescKeyTyped(evt);
			}
		});

		btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/ok.png"))); // NOI18N
		btnOk.setToolTipText("Aceptar");
		btnOk.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnOkMousePressed(evt);
			}
		});

		btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/cancel.png"))); // NOI18N
		btnCancel.setToolTipText("Cancelar");
		btnCancel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnCancelMousePressed(evt);
			}
		});

		txtIdConcepto.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtIdConcepto.setEditable(false);
		txtIdConcepto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtIdConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14));

		javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(
				pnlData);
		pnlData.setLayout(pnlDataLayout);
		pnlDataLayout
				.setHorizontalGroup(pnlDataLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pnlDataLayout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																pnlDataLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblIdConcepto,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				120,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				txtIdConcepto,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																pnlDataLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblConceptoDesc,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				120,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				txtConceptoDesc,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				480,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(45, 45, 45))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								pnlDataLayout
										.createSequentialGroup()
										.addContainerGap(548, Short.MAX_VALUE)
										.addComponent(btnCancel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnOk).addContainerGap()));
		pnlDataLayout
				.setVerticalGroup(pnlDataLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pnlDataLayout
										.createSequentialGroup()
										.addGap(72, 72, 72)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																lblIdConcepto)
														.addComponent(
																txtIdConcepto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(10, 10, 10)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																lblConceptoDesc)
														.addComponent(
																txtConceptoDesc,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												71, Short.MAX_VALUE)
										.addGroup(
												pnlDataLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(btnOk)
														.addComponent(btnCancel))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 676,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pnlData, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			if (OnNew) 
				newData();
			else
				loadData(this.concepto);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmConcepto.btnCancelMousePressed()", he);
		}
	}

	private void btnOkMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			saveData(true);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmConcepto.btnOkMousePressed()", he);
		}
	}

	private void txtConceptoDescKeyTyped(java.awt.event.KeyEvent evt) {
		try {
			Util.keyTyped(txtConceptoDesc, evt, 25);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmConcepto.txtConceptoDescKeyTyped()", he);
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOk;
	private javax.swing.JLabel lblIdConcepto;
	private javax.swing.JLabel lblConceptoDesc;
	public javax.swing.JPanel pnlData;
	private javax.swing.JFormattedTextField txtIdConcepto;
	private javax.swing.JTextField txtConceptoDesc;
	// End of variables declaration//GEN-END:variables

}