/*
 * FrmParamFacturas.java
 *
 * Created on __DATE__, __TIME__
 */

package winUIPackage;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashSet;

import java.util.Set;



import entitiesPackage.Entity;
import entitiesPackage.Message;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import sessionPackage.MySession;

/**
 *
 * @author  __USER__
 */
public class FrmGeneraLiquidacionRetorno extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MySession session;
	private java.awt.Frame parent;
	private Entity entity = new Entity();
	SwingWorker worker;
	
	boolean toModify = false;

	/** Creates new form FrmParamFacturas */
	public FrmGeneraLiquidacionRetorno(java.awt.Frame parent, MySession session,
			boolean modal) {
		super(parent, modal);
		try {
			this.session = session;
			this.parent = parent;
			entity.setSession(session);
			initComponents();
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent, "FrmGeneraLiquidacionRetorno()", he);
		}
	}

	private void configureKeys() {
		try {
			Set<AWTKeyStroke> teclasTab = new HashSet<AWTKeyStroke>();
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_DOWN, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_TAB, 0));
			this.setFocusTraversalKeys(
					KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, teclasTab);

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmGeneraLiquidacionRetorno.configureKeys", he);
		}
	}


        private boolean validateData() {

		try {
			if (txtImporteKilo.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar el importe por kilo.");
				txtImporteKilo.requestFocus();
				return (false);
			} else {
				try {
					txtImporteKilo.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
							"El tipo de datos indicado no es válido.");
					txtImporteKilo.requestFocus();
					return (false);
				}
			}
                        
                        if (txtPorcentajeKilos.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar el porcentaje de kilos a bonificar.");
				txtPorcentajeKilos.requestFocus();
				return (false);
			} else {
				try {
					txtPorcentajeKilos.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
							"El tipo de datos indicado no es válido.");
					txtPorcentajeKilos.requestFocus();
					return (false);
				}
			}
                        
                        if (txtEjericioContable.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar un ejercicio contable.");
				txtEjericioContable.requestFocus();
				return (false);
			} else {
				try {
					txtEjericioContable.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
							"El tipo de datos indicado no es válido.");
					txtEjericioContable.requestFocus();
					return (false);
				}
			}
                        
                        if (txtNumeroBonificacion.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar un número de la bonificación en el año contable.");
				txtNumeroBonificacion.requestFocus();
				return (false);
			} else {
				try {
					txtNumeroBonificacion.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
							"El tipo de datos indicado no es válido.");
					txtNumeroBonificacion.requestFocus();
					return (false);
				}
			}
                        
                        if (txtFecha.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar una fecha.");
				txtFecha.requestFocus();
				return (false);
			} else {
				try {
					txtFecha.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
							"El tipo de datos indicado no es válido.");
					txtFecha.requestFocus();
					return (false);
				}
			}
                        
                        if (txtTitulo.getText().equals("")) {
				Message.ShowValidateMessage(parent, "Debe indicar un título.");
				txtTitulo.requestFocus();
				return (false);
			} 
                        
			return (true);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmGeneraLiquidacionRetorno.validateData()", he);
			return (false);
		}
	}
        
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        lblEjercicio = new javax.swing.JLabel();
        lblImporteKilo = new javax.swing.JLabel();
        txtImporteKilo = new javax.swing.JFormattedTextField();
        lblPorcentajeKilos = new javax.swing.JLabel();
        txtPorcentajeKilos = new javax.swing.JFormattedTextField();
        lblEjericioContable = new javax.swing.JLabel();
        txtEjericioContable = new javax.swing.JFormattedTextField();
        lblNumeroBonificacion = new javax.swing.JLabel();
        txtNumeroBonificacion = new javax.swing.JFormattedTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generación de liquidaciones");
        setResizable(false);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/ok.png"))); // NOI18N
        btnOk.setToolTipText("Aceptar");
        btnOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
        });

        lblEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjercicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEjercicio.setText("Generar la liquidación de Retorno");
        lblEjercicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblImporteKilo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblImporteKilo.setForeground(new java.awt.Color(255, 0, 0));
        lblImporteKilo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImporteKilo.setText("Importe kilo");
        lblImporteKilo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtImporteKilo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtImporteKilo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0000"))));
        txtImporteKilo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtImporteKilo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPorcentajeKilos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPorcentajeKilos.setForeground(new java.awt.Color(255, 0, 0));
        lblPorcentajeKilos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPorcentajeKilos.setText("Porcentaje kilos");
        lblPorcentajeKilos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtPorcentajeKilos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPorcentajeKilos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0000"))));
        txtPorcentajeKilos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPorcentajeKilos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEjericioContable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjericioContable.setForeground(new java.awt.Color(255, 0, 0));
        lblEjericioContable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEjericioContable.setText("Ejercicio contable");
        lblEjericioContable.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtEjericioContable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEjericioContable.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEjericioContable.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEjericioContable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNumeroBonificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroBonificacion.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroBonificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroBonificacion.setText("Número bonificación");
        lblNumeroBonificacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtNumeroBonificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNumeroBonificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNumeroBonificacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumeroBonificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 0, 0));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha de liquidación");

        txtFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitulo.setText("Titulo");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTitulo.setAutoscrolls(false);
        txtTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTitulo.setName("nombre"); // NOI18N
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblImporteKilo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtImporteKilo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblPorcentajeKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtPorcentajeKilos, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblEjericioContable, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblNumeroBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(10, 10, 10)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNumeroBonificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                                .addComponent(txtEjericioContable)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblEjercicio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteKilo)
                    .addComponent(txtImporteKilo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentajeKilos)
                    .addComponent(txtPorcentajeKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEjericioContable)
                    .addComponent(txtEjericioContable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroBonificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(btnOk)
                .addContainerGap())
        );

        lblEjercicio.getAccessibleContext().setAccessibleName("Ejercicio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyTyped

	private Object DoLiquidacion() throws ParseException {
		try {
                    if (validateData()) {
                            Integer cont = 0;
                            Float importekilo = ((Number) txtImporteKilo.getValue()).floatValue();
                            Float porcentajekilos = ((Number) txtPorcentajeKilos.getValue()).floatValue();
                            int ejercicioContable = ((Number) txtEjericioContable.getValue()).intValue();
                            int numeroBonificacion = ((Number) txtNumeroBonificacion.getValue()).intValue();
                            java.util.Date fecha = new SimpleDateFormat("dd/MM/yyyy").parse(txtFecha.getValue().toString()); 
                            String titulo = txtTitulo.getText();
                            
                            try {
                                entity.LiquidacionRetornoGenerate(parent,importekilo,porcentajekilos, ejercicioContable, numeroBonificacion, fecha, titulo);                                  
                            } catch (SQLException ex) {
                                    Message.ShowErrorMessage(parent,
                                                    "FrmGeneraLiquidacionRetorno", ex
                                                                    .getMessage());
                                    return null;
                            }

                    }
                    return "Completado";
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmGeneraLiquidacionRetorno.DoLiquidacion()", he);
			return "Error";
		} 
	}

	private void btnOkMousePressed(java.awt.event.MouseEvent evt) {
		try {
                    btnOk.setEnabled(false);
                    worker = new SwingWorker() {
                                    public Object construct() {
                                        try {
                                            return DoLiquidacion();
                                        } catch (ParseException ex) {
                                            Logger.getLogger(FrmGeneraLiquidacionRetorno.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                        return null;
                                    }

                                    public void finished() {
                                            btnOk.setEnabled(true);
                                    }
                            };
                            worker.start();
		}
		catch (RuntimeException he) {
			Message.ShowRuntimeError(this,
					"FrmGeneraLiquidacionRetorno.btnOkMousePressed()", he);
		}
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblEjercicio;
    private javax.swing.JLabel lblEjericioContable;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImporteKilo;
    private javax.swing.JLabel lblNumeroBonificacion;
    private javax.swing.JLabel lblPorcentajeKilos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField txtEjericioContable;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtImporteKilo;
    private javax.swing.JFormattedTextField txtNumeroBonificacion;
    private javax.swing.JFormattedTextField txtPorcentajeKilos;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}