/*
 * FrmParamFacturas.java
 *
 * Created on __DATE__, __TIME__
 */

package winUIPackage;

import java.awt.AWTKeyStroke;
import java.awt.Cursor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.HashSet;
import java.util.Set;

import entitiesPackage.Message;
import reportsPackage.FacturaServicios;
import sessionPackage.MySession;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JFormattedTextField;
import javax.swing.border.BevelBorder;

/**
 *
 * @author  __USER__
 */
public class FrmInformeFacturas extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MySession session;
	private java.awt.Frame parent;
	private int factura = 0;

	/** Creates new form FrmParamFacturas 
	 * @wbp.parser.constructor*/
	public FrmInformeFacturas(java.awt.Frame parent, MySession session,
			boolean modal) {
		super(parent, modal);
		try {
			this.session = session;
			this.parent = parent;
			initComponents();
			
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent, "FrmInformeFacturas()", he);
		}
	}
	
	public FrmInformeFacturas(java.awt.Frame parent, MySession session,
			boolean modal, int Factura) {
		super(parent, modal);
		try {
			
			this.session = session;
			this.parent = parent;
			this.factura = Factura;
			initComponents();
			txtFacturaDesde.setText(Integer.toString(factura));
			txtFacturaHasta.setText(Integer.toString(factura));
			txtFacturaDesde.setEnabled(false);
			txtFacturaHasta.setEnabled(false);
			txtCuentaBancaria.requestFocus();
			
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent, "FrmInformeFacturas()", he);
		}
	}

	private void configureKeys() {
		try {
			Set<AWTKeyStroke> teclasTab = new HashSet<AWTKeyStroke>();
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_DOWN, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_TAB, 0));
			this.setFocusTraversalKeys(
					KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, teclasTab);

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent, "FrmInformeFacturas.configureKeys",
					he);
		}
	}
	private boolean validateData() {

		try {
			if (txtFacturaDesde.getText().equals("")) {
				Message.ShowValidateMessage(parent,
						"Debe indicar la factura desde.");
				txtFacturaDesde.requestFocus();
				return (false);
			}
			else {
				try {
					txtFacturaDesde.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
					"El tipo de datos indicado no es válido.");
					txtFacturaDesde.requestFocus();
					return (false);
				}
			}
			if (txtFacturaHasta.getText().equals("")) {
				Message.ShowValidateMessage(parent,
						"Debe indicar la factura hasta.");
				txtFacturaHasta.requestFocus();
				return (false);
			}
			else {
				try {
					txtFacturaHasta.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
						"El tipo de datos indicado no es válido.");
					txtFacturaHasta.requestFocus();
					return (false);
				}
			}
			if (!txtCuentaBancaria.getText().equals("")) {
				try {
					txtCuentaBancaria.commitEdit();
				} catch (ParseException e) {
					Message.ShowValidateMessage(parent,
						"El tipo de datos indicado no es válido.");
					txtCuentaBancaria.requestFocus();
					return (false);
				}
			}

			return (true);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmInformeFacturas.validateData()", he);
			return (false);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		lblFacturaDesde = new javax.swing.JLabel();
		txtFacturaDesde = new javax.swing.JFormattedTextField();
		lblFacturaHasta = new javax.swing.JLabel();
		txtFacturaHasta = new javax.swing.JFormattedTextField();
		btnCancel = new javax.swing.JButton();
		btnOk = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Informe de facturas de servicio");

		lblFacturaDesde.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblFacturaDesde.setForeground(new java.awt.Color(255, 0, 0));
		lblFacturaDesde
				.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblFacturaDesde.setText("Número de factura desde");
		lblFacturaDesde
				.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		txtFacturaDesde.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtFacturaDesde
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		txtFacturaDesde.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtFacturaDesde.setFont(new java.awt.Font("Segoe UI", 0, 14));

		lblFacturaHasta.setFont(new java.awt.Font("Segoe UI", 1, 14));
		lblFacturaHasta.setForeground(new java.awt.Color(255, 0, 0));
		lblFacturaHasta
				.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblFacturaHasta.setText("Número de factura hasta");
		lblFacturaHasta
				.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		txtFacturaHasta.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		txtFacturaHasta
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		txtFacturaHasta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		txtFacturaHasta.setFont(new java.awt.Font("Segoe UI", 0, 14));

		btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/cerrar.png")));
		btnCancel.setToolTipText("Cancelar");
		btnCancel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnCancelMousePressed(evt);
			}
		});

		btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagesPackage/ok.png")));
		btnOk.setToolTipText("Aceptar");
		btnOk.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btnOkMousePressed(evt);
			}
		});
		
		lblCuentaBancaria = new JLabel();
		lblCuentaBancaria.setText("Cuenta bancaria");
		lblCuentaBancaria.setHorizontalTextPosition(SwingConstants.RIGHT);
		lblCuentaBancaria.setHorizontalAlignment(SwingConstants.RIGHT);
		lblCuentaBancaria.setForeground(Color.RED);
		lblCuentaBancaria.setFont(new Font("Segoe UI", Font.BOLD, 14));
		
		txtCuentaBancaria = new JFormattedTextField();
		txtCuentaBancaria.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		txtCuentaBancaria.setHorizontalAlignment(SwingConstants.LEFT);
		txtCuentaBancaria.setFont(new Font("Segoe UI", Font.PLAIN, 14));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(29)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
									.addComponent(lblFacturaDesde, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.UNRELATED))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblFacturaHasta, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
									.addGap(10)))
							.addGap(10)
							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtFacturaHasta)
								.addComponent(txtFacturaDesde, GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
							.addPreferredGap(ComponentPlacement.RELATED, 217, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addGap(37)
									.addComponent(lblCuentaBancaria, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(txtCuentaBancaria, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
									.addContainerGap()
									.addComponent(btnCancel)
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(btnOk)))
							.addGap(16)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(42)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblFacturaDesde)
						.addComponent(txtFacturaDesde, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblFacturaHasta)
						.addComponent(txtFacturaHasta, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(txtCuentaBancaria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblCuentaBancaria, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addGap(24)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(btnCancel)
						.addComponent(btnOk))
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
	}

	private void btnOkMousePressed(java.awt.event.MouseEvent evt) {
		try {
			if (validateData()) {
				Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
				setCursor(hourglassCursor);
				FacturaServicios report = new FacturaServicios(parent);
				report.runReporte(session.getEmpresa().getIdEmpresa(), session
						.getEjercicio().getEjercicio(),
						((Number) txtFacturaDesde.getValue()).intValue(),
						((Number) txtFacturaHasta.getValue()).intValue(),
						txtCuentaBancaria.getText());
				Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
				setCursor(normalCursor);
			}
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmInformeFacturas.btnOkMousePressed()", he);
		}
	}

	private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			this.dispose();
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parent,
					"FrmInformeFacturas.btnCancelMousePressed()", he);
		}
	}

	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOk;
	private javax.swing.JLabel lblFacturaDesde;
	private javax.swing.JLabel lblFacturaHasta;
	private javax.swing.JFormattedTextField txtFacturaDesde;
	private javax.swing.JFormattedTextField txtFacturaHasta;
	private JLabel lblCuentaBancaria;
	private JFormattedTextField txtCuentaBancaria;
}
