/*
 * FrmBanco.java
 *
 * Created on __DATE__, __TIME__
 */

package winUIPackage;

import java.awt.AWTKeyStroke;
import java.awt.Cursor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.ReplicationMode;
import org.hibernate.Transaction;

import sessionPackage.MySession;

import entitiesPackage.Entity;
import entitiesPackage.Message;
import entitiesPackage.Tiposgasto;
import entitiesPackage.TiposgastoId;

/**
 *
 * @author  SANTI DIAZ
 */
public class FrmTipoGasto extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	Tiposgasto tipogasto;

	private java.awt.Frame parentFrame;
	private MySession session;
	private boolean OnNew = false;
	private Entity entity = new Entity();

	public java.awt.Frame getParentFrame() {
		return this.parentFrame;
	}

	public void setParentFrame(java.awt.Frame parentFrame) {
		this.parentFrame = parentFrame;
	}

	public void setSession(MySession session) {
		this.session = session;
	}

	public MySession getSession() {
		return session;
	}

	/** Creates new form FrmBanco */
	public FrmTipoGasto() {
		initComponents();
	}

	public FrmTipoGasto(java.awt.Frame parent, MySession session) {
		try {
			initComponents();
			this.parentFrame = parent;
			this.setSession(session);
			entity.setSession(session);
			configureKeys();

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmTipoGasto()", he);
		}
	}

	private void configureKeys() {
		try {
			Set<AWTKeyStroke> teclasTab = new HashSet<AWTKeyStroke>();
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_DOWN, 0));
			teclasTab.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_TAB, 0));
			pnlData.setFocusTraversalKeys(
					KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, teclasTab);

		} catch (RuntimeException he) {
			Message.ShowRuntimeError(parentFrame, "FrmTipoGasto.configureKeys",
					he);
		}
	}

	public void loadData(Tiposgasto entity) {

		try {
			this.tipogasto = entity;
			txtIdTipoGasto.setValue(entity.getId().getIdTipoGasto());
			txtDescTipoGasto.setText(entity.getDescTipoGasto());
			OnNew = false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmTipoGasto.loadData()",
					he);
		}
	}

	public void newData() {
		try {
			this.tipogasto = new Tiposgasto();
			txtIdTipoGasto.setText("");
			txtDescTipoGasto.setText("");
			OnNew = true;
		} catch (RuntimeException he) {
			Message
					.ShowRuntimeError(this.parentFrame, "FrmTipoGasto.newData()",
							he);
		}

	}

	public boolean saveData(Boolean showmessage) {

		try {
			if (validateData()) {

				Transaction transaction = session.getSession()
						.beginTransaction();
				if (OnNew) {
					txtIdTipoGasto.setValue(entity.newId(this, "Tiposgasto",
							"id.idTipoGasto"));
					TiposgastoId tipogastoid = new TiposgastoId();
					tipogastoid.setEmpresas(session.getEmpresa());
					tipogastoid.setEjercicios(session.getEjercicio());
					tipogastoid.setIdTipoGasto((Integer) txtIdTipoGasto.getValue());
					tipogasto.setId(tipogastoid);
				}
				if (!txtDescTipoGasto.getText().equals(""))
					tipogasto.setDescTipoGasto(txtDescTipoGasto.getText());
				else
					tipogasto.setDescTipoGasto(null);
				tipogasto.setLmd(new Date());
				tipogasto.setSid("Santi");
				tipogasto.setVersion(1);
				session.getSession()
						.replicate(tipogasto, ReplicationMode.OVERWRITE);
				session.getSession().saveOrUpdate(tipogasto);
				session.getSession().flush();
				if (transaction.isActive()) {
					transaction.commit();
				}
				session.getSession().close();
				if (showmessage)
					Message.ShowSaveSuccesfull(pnlData);
				OnNew = false;
				FrmTiposGasto.runSearchQuery();
				return true;
			}
			else
				return false;
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame, "FrmTipoGasto.saveData()",
					he);
			return false;
		}
	}

	private boolean validateData() {

		try {
			if (txtDescTipoGasto.getText().equals("")) {
				Message.ShowValidateMessage(pnlData,
						"Debe indicar una descripci�n para el tipo de gasto.");
				txtDescTipoGasto.requestFocus();
				return (false);
			}

			return (true);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmTipoGasto.validateData()", he);
			return false;
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
//GEN-BEGIN:initComponents
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

pnlData = new javax.swing.JPanel();
lblIdTipoGasto = new javax.swing.JLabel();
lblDescTipoGasto = new javax.swing.JLabel();
txtDescTipoGasto = new javax.swing.JTextField();
btnOk = new javax.swing.JButton();
btnCancel = new javax.swing.JButton();
txtIdTipoGasto = new javax.swing.JFormattedTextField();

pnlData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
pnlData.setName("pnlData");

lblIdTipoGasto.setFont(new java.awt.Font("Segoe UI", 1, 14));
lblIdTipoGasto.setForeground(new java.awt.Color(255, 0, 0));
lblIdTipoGasto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
lblIdTipoGasto.setText("Id");

lblDescTipoGasto.setFont(new java.awt.Font("Segoe UI", 1, 14));
lblDescTipoGasto.setForeground(new java.awt.Color(255, 0, 0));
lblDescTipoGasto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
lblDescTipoGasto.setText("Tipo de gasto");

txtDescTipoGasto.setFont(new java.awt.Font("Segoe UI", 0, 14));
txtDescTipoGasto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
txtDescTipoGasto.setAutoscrolls(false);
txtDescTipoGasto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
txtDescTipoGasto.setName("");
txtDescTipoGasto.addKeyListener(new java.awt.event.KeyAdapter() {
public void keyTyped(java.awt.event.KeyEvent evt) {
txtDescTipoGastoKeyTyped(evt);
}
});

btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/ok.png"))); // NOI18N
btnOk.setToolTipText("Aceptar");
btnOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
btnOkMousePressed(evt);
}
});

btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/cancel.png"))); // NOI18N
btnCancel.setToolTipText("Cancelar");
btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
btnCancelMousePressed(evt);
}
});

txtIdTipoGasto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
txtIdTipoGasto.setEditable(false);
txtIdTipoGasto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
txtIdTipoGasto.setFont(new java.awt.Font("Segoe UI", 0, 14));

javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
pnlData.setLayout(pnlDataLayout);
pnlDataLayout.setHorizontalGroup(
pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(pnlDataLayout.createSequentialGroup()
.addGap(18, 18, 18)
.addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(pnlDataLayout.createSequentialGroup()
.addComponent(lblIdTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(10, 10, 10)
.addComponent(txtIdTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(pnlDataLayout.createSequentialGroup()
.addComponent(lblDescTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(10, 10, 10)
.addComponent(txtDescTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(45, 45, 45))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataLayout.createSequentialGroup()
.addContainerGap(548, Short.MAX_VALUE)
.addComponent(btnCancel)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(btnOk)
.addContainerGap())
);
pnlDataLayout.setVerticalGroup(
pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(pnlDataLayout.createSequentialGroup()
.addGap(72, 72, 72)
.addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(lblIdTipoGasto)
.addComponent(txtIdTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(10, 10, 10)
.addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(lblDescTipoGasto)
.addComponent(txtDescTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
.addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(btnOk)
.addComponent(btnCancel))
.addContainerGap())
);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
this.setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);
}// </editor-fold>
//GEN-END:initComponents

	private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			if (OnNew) 
				newData();
			else
				loadData(this.tipogasto);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmTipoGasto.btnCancelMousePressed()", he);
		}
	}

	private void btnOkMousePressed(java.awt.event.MouseEvent evt) {
		try {
			Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
			setCursor(hourglassCursor);
			saveData(true);
			Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
			setCursor(normalCursor);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmTipoGasto.btnOkMousePressed()", he);
		}
	}

	private void txtDescTipoGastoKeyTyped(java.awt.event.KeyEvent evt) {
		try {
			Util.keyTyped(txtDescTipoGasto, evt, 30);
		} catch (RuntimeException he) {
			Message.ShowRuntimeError(this.parentFrame,
					"FrmTipoGasto.txtDescTipoGastoKeyTyped()", he);
		}
	}

//GEN-BEGIN:variables
// Variables declaration - do not modify
private javax.swing.JButton btnCancel;
private javax.swing.JButton btnOk;
private javax.swing.JLabel lblDescTipoGasto;
private javax.swing.JLabel lblIdTipoGasto;
public javax.swing.JPanel pnlData;
private javax.swing.JTextField txtDescTipoGasto;
private javax.swing.JFormattedTextField txtIdTipoGasto;
// End of variables declaration//GEN-END:variables

}
